/*
 * GroupSelector.java
 *
 * Created on January 5, 2006, 11:42 AM
 */

package com.pmiapp.apcs;

/**
 * Form to allow selection of one of a number of groups.  Automatically
 * adds "*Default*" as the first available group.
 * @author Ron V. Webber
 */
public class GroupSelector extends javax.swing.JDialog {
    
    /**
     * Creates new form to select which group to switch to.
     * @param parent Frame of caller
     * @param groupList String array of names of groups, not including the "*Default*"
     * group.
     * @param currentIndex index into string array for current group.  Set to -1 to
     * signify that the "*Default*" group is current.
     */
    public GroupSelector(java.awt.Frame parent, String[] groupList, int currentIndex) {
        super(parent, true);
        initComponents();
        String[] groupList2 = new String[groupList.length+1];
        groupList2[0]="*Default*";
        System.arraycopy(groupList, 0, groupList2, 1, groupList.length);
        jList1.setListData(groupList2);
        jList1.setSelectedIndex(currentIndex+1);
        currentSelection=-1; // signifies no actual selection
        this.setLocationRelativeTo(parent);
    }
    
    private int currentSelection;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setTitle("Select Group");
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        currentSelection=jList1.getSelectedIndex();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Get index of selected group
     * @return -1 if nothing selected, 0 if "*Default*" group selected, >0
     * if one of the named groups is selected.  Decrement by 1 to get
     * the actual 0-based index into the list of groups.
     */
    protected int getSelectedIndex() {
        return currentSelection;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
