/*
 * Target.java
 *
 * Created on Mar 1, 2009, 10:09:34 PM
 */

package com.pmiapp.apcs;

import java.io.*;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ron
 */
public class Target extends JDialog {

    /** Creates new form Target */
    public Target(java.awt.Frame parent, String basePath) {
        super(parent, true);
        //this.basePath=basePath;
        initComponents();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [50][4], new String [] {
                    "No", "Pressure", "Hold Time", "Temperature" } ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        java.lang.Float f0 = new java.lang.Float(0);
        for (int i=0; i<50; i++) {
            jTable1.getModel().setValueAt(""+(i+1),i,0);
            jTable1.getModel().setValueAt(f0,i,1);
            jTable1.getModel().setValueAt(f0,i,2);
            jTable1.getModel().setValueAt(f0,i,3);
        }
        jScrollPane1.setViewportView(jTable1);
        tpfChooser = new JFileChooser();
        tpfChooser.addChoosableFileFilter(new TpfFilter());
        tpfChooser.setCurrentDirectory(new File(basePath,"parms"));
        dataAvailable=false;
        targetFile="Not Defined";
    }

    //private String basePath;
    private JFileChooser tpfChooser;
    private boolean dataAvailable;
    private int rowsAvailable;
    private String targetFile;

    private void clear() {
        java.lang.Float f0 = new java.lang.Float(0);
        for (int i=0; i<50; i++) {
            jTable1.getModel().setValueAt(f0,i,1);
            jTable1.getModel().setValueAt(f0,i,2);
            jTable1.getModel().setValueAt(f0,i,3);
        }
    }

    public boolean isDataAvailable() {
        return dataAvailable;
    }

    public float[] getPressureData() {
        if (dataAvailable) {
            float[] f = new float[rowsAvailable];
            for (int i=0; i<rowsAvailable; i++)
                f[i]=(Float)jTable1.getModel().getValueAt(i,1);
            return f;
        } else
            return null;
    }

    public float[] getTimeData() {
        if (dataAvailable) {
            float[] f = new float[rowsAvailable];
            for (int i=0; i<rowsAvailable; i++)
                f[i]=(Float)jTable1.getModel().getValueAt(i,2);
            return f;
        } else
            return null;
    }

    public float[] getTempData() {
        if (dataAvailable) {
            float[] f = new float[rowsAvailable];
            for (int i=0; i<rowsAvailable; i++)
                f[i]=(Float)jTable1.getModel().getValueAt(i,3);
            return f;
        } else
            return null;
    }
    public String getTargetFile() {
        return targetFile;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setTitle("Pressure Target Input");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Pressure:           PSI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Time:                Sec.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 359;
        gridBagConstraints.ipady = 224;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 9, 0, 7);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        getContentPane().add(jButton3, gridBagConstraints);

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        getContentPane().add(jButton4, gridBagConstraints);

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        getContentPane().add(jButton5, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Value Wizard"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, -1));

        jLabel4.setText("Increment by:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel3.setText("Starting Value:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Pressure");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Time(Sec.)");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Time(Min.)");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Temperature");
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel5.setText("Total Values:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 40, -1));

        jButton6.setText("Add Values");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tpfChooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION) {
            try {
                targetFile=tpfChooser.getSelectedFile().getPath();
                BufferedReader in = new BufferedReader(
                        new FileReader(tpfChooser.getSelectedFile()));
                clear();
                try {
                    for (int i=0; i<50; i++) {
                        String s = in.readLine();
                        if (s==null) break;
                        String[] vals = s.split(" ",3);
                        if (vals.length<3) break;
                        Float f0 = new Float(vals[0]);
                        Float f1 = new Float(vals[1]);
                        Float f2 = new Float(vals[2]);
                        // original vb6 program terminated reading
                        // if the first value was 0
                        if (f0==0) break;
                        jTable1.getModel().setValueAt(f0,i,1);
                        jTable1.getModel().setValueAt(f1,i,2);
                        jTable1.getModel().setValueAt(f2,i,3);
                    }
                }
                catch (NumberFormatException e3) {
                    JOptionPane.showMessageDialog(this,"Improper number format");
                }
                in.close();
            }
            catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this,"File Not Found");
            }
            catch (IOException e2) {
                JOptionPane.showMessageDialog(this,"Error reading file");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tpfChooser.showSaveDialog(this)==JFileChooser.APPROVE_OPTION) {
            File f = tpfChooser.getSelectedFile();
            // make sure extension is ".tpf"
            // note that getExtension always returns a lower case string
            if (!com.pmiapp.common.TxtFilter.getExtension(f).equals("tpf")) {
                String s=f.getName();
                if (s.endsWith(".")==false)
                    s=s+".";
                f=new File(f.getParentFile(),s+"tpf");
            }
            try {
                targetFile=f.getPath();
                PrintWriter out = new PrintWriter(f);
                for (int i=0; i<50; i++) {
                    out.print((Float)jTable1.getModel().getValueAt(i,1));
                    out.print(" ");
                    Float ff = (Float)jTable1.getModel().getValueAt(i,2);
                    out.print(ff);
                    out.print(" ");
                    ff = (Float)jTable1.getModel().getValueAt(i,3);
                    out.println(ff);
                    
                    // original vb6 program terminated output after second value was 0
                    if (ff==0) break;
                }
                out.close();
                if (out.checkError())
                    JOptionPane.showMessageDialog(this,"Error writing to file");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this,"Error opening file for writing");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i;
        for (i=0; i<50; i++) {
            Float f1 = (Float)jTable1.getModel().getValueAt(i,1);
            Float f2 = (Float)jTable1.getModel().getValueAt(i,2);
            Float f3 = (Float)jTable1.getModel().getValueAt(i,3);
            if ((f1==0) || (f2==0) || (f3==0)) break;
        }
        rowsAvailable=i;
        dataAvailable=(i>0);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void ClearColumn(int column)
    {
        java.lang.Float f0 = new java.lang.Float(0);
            for (int i=0; i<50; i++) {
                jTable1.getModel().setValueAt(f0,i,column);
            }
    }
    public void BuildColumn(int column, int startVal, int incVal, int totalVal)
    {
        int lastValue = startVal;
        for(int i = 0; i < totalVal; i++)
            {
                java.lang.Float f0 = new java.lang.Float(lastValue);
                jTable1.getModel().setValueAt(f0,i,column);
                lastValue += incVal;
            }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int increment = 0;
        int startValue = 0;
        int totalValues = 0;
         try
            {
                increment = Integer.parseInt(jTextField2.getText());
                
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Please input a whole number for a starting value.");
                return;
            }
            try
            {
                startValue= Integer.parseInt(jTextField1.getText());
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Please input a whole number for an increment.");
                return;
            }
            try
            {
                totalValues = Integer.parseInt(jTextField3.getText());
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Please input a whole number for a total number of values.");
                return;
            }
            if (totalValues > 50)
            {
                JOptionPane.showMessageDialog(this, "Please input a whole number of 50 or less for a total number of values.");
                return;
            }
        if (jRadioButton1.isSelected())
        {
            //check to make sure everything is kosher cooking.
           
            //if everything is cool, clear any old values first
            ClearColumn(1);
            BuildColumn(1, startValue, increment, totalValues);
            
        }
        if (jRadioButton2.isSelected())
        {
            
            ClearColumn(2);
            BuildColumn(2, startValue, increment, totalValues);
           
        }
        if (jRadioButton3.isSelected())
        {
            ClearColumn(2);
            BuildColumn(2, startValue * 60, increment * 60, totalValues);
        }
        if (jRadioButton4.isSelected())
        {
            //build temperature column
            ClearColumn(3);
            BuildColumn(3, startValue, increment, totalValues);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Target dialog = new Target(new JFrame(), "c:\\temp");
                dialog.setVisible(true);
                System.exit(0);
            }
        });
    }
}
